### ISSUE TITLE
Your html should be inside of the body tag.

### ISSUE THREAD

**Issue by farishkash** [robbiewolff/prj-rev-bwfs-dasmoto#1]
https://github.com/robbiewolff/prj-rev-bwfs-dasmoto/blob/938d1d76368cd4febd3df0895e6c1b8a5c68e9c2/Arts%20and%20Crafts/index.html#L22-L26

You have all of your HTML before the body tag.

**Comment by robbiewolff** [comment]
Got it. Fixed.
